FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json ./

COPY prisma ./prisma/ 

RUN npm ci

COPY . .

EXPOSE 8080

CMD ["sh", "-c", "./node_modules/.bin/prisma migrate deploy && npm run start:dev"]